In [2]:
import selenium
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import warnings
warnings.filterwarnings("ignore")
import time

In [3]:
PATH = r'C:\chromedriver\chromedriver.exe'

In [3]:
driver = webdriver.Chrome()

In [4]:
driver.get("https://www.shine.com/")

timeout = 5
try:
    element_present = EC.presence_of_element_located((By.ID, 'main'))
    WebDriverWait(driver, timeout).until(element_present)
except TimeoutException:
    print("Timed out waiting for page to load")
finally:
    print("Page loaded")

Timed out waiting for page to load
Page loaded

In [5]:
designation = driver.find_element(By.XPATH,"//div[@id='webSearchBar']/input").click()

In [47]:
designation.send_keys('Data Analyst')

AttributeError: 'NoneType' object has no attribute 'send_keys'

In [6]:
location = driver.find_element(By.XPATH,"//div[@id='select_container_id_loc']/input").click()

In [53]:
location.send_keys('Bangalore')

AttributeError: 'NoneType' object has no attribute 'send_keys'

In [7]:
search=driver.find_element(By.CLASS_NAME,"btn btn-secondary undefined")
search.click()

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".btn btn-secondary undefined"}
  (Session info: chrome=116.0.5845.111); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x00007FF66A9752A2+57122]
	(No symbol) [0x00007FF66A8EEA92]
	(No symbol) [0x00007FF66A7BE3AB]
	(No symbol) [0x00007FF66A7F7D3E]
	(No symbol) [0x00007FF66A7F7E2C]
	(No symbol) [0x00007FF66A830B67]
	(No symbol) [0x00007FF66A81701F]
	(No symbol) [0x00007FF66A82EB82]
	(No symbol) [0x00007FF66A816DB3]
	(No symbol) [0x00007FF66A7ED2B1]
	(No symbol) [0x00007FF66A7EE494]
	GetHandleVerifier [0x00007FF66AC1EF82+2849794]
	GetHandleVerifier [0x00007FF66AC71D24+3189156]
	GetHandleVerifier [0x00007FF66AC6ACAF+3160367]
	GetHandleVerifier [0x00007FF66AA06D06+653702]
	(No symbol) [0x00007FF66A8FA208]
	(No symbol) [0x00007FF66A8F62C4]
	(No symbol) [0x00007FF66A8F63F6]
	(No symbol) [0x00007FF66A8E67A3]
	BaseThreadInitThunk [0x00007FF882367614+20]
	RtlUserThreadStart [0x00007FF8843426B1+33]

In [47]:
job=[]

In [8]:
# Extract job title 

title = driver.find_elements(By_XPATH,"//div[@id='1']/div[2]/div/div/h2/a]")

for i in title[0:10]:
    
    titles=i.text
    Job.append(titles)
    
#title[0:10]

NameError: name 'By_XPATH' is not defined

In [40]:
print(len(job_title))

0

In [53]:
title_tag = driver.find_elements_by_xpath(2/a")

title_tag[0:10]

AttributeError: 'WebDriver' object has no attribute 'find_elements_by_xpath'

In [34]:
print(job_title)

[]

In [ ]:
title_tag = driver.find_elements_by_xpath("//a[@class = 'title fw500 ellipsis']")

title_tag[0:10]

In [35]:
# Creating Dataframe

df = pd.DataFrame({'Title':job_title})

In [32]:
df

Empty DataFrame
Columns: [Title]
Index: []

In [ ]:
# print dataframe.

df

# Question 4

In [4]:
driver = webdriver.Chrome()

In [5]:
url='https://www.flipkart.com/'
driver.get(url)

In [17]:
product = driver.find_element(By.XPATH,"/html/body/div/div/div[1]/div[1]/div[2]/div[2]/form/div/div/input")

In [18]:
product.send_keys('sunglasses')

In [19]:
#btn=driver.find_element(By.XPATH,"/html/body/div/div/div[1]/div[1]/div[2]/div[2]/form/div/button/svg/g/path[2]")

btn=driver.find_element(By.XPATH,"//*[@id='container']/div/div[1]/div[1]/div[2]/div[2]/form/div/button")

In [20]:
btn.click()

In [50]:
#creating functions to scrape data
import time

In [51]:
def scrape_brand_name(url):
    brand=[]
    driver.get(url)
    try:
        brand_el=driver.find_elements_by_xpath("//div[@class='_2WkVRV']")
        time.sleep(3)
        
        for i in brand_el:
            
            brand.append(i.text)
            driver.execute_script("window.scrollBy(0,document.body.scrollHeight0)")
            
        return brand
    except StaleElementReferenceException as e:
        print("exception raised",e)

In [52]:
def scrape_product_des(url):
    product_des=[]
    driver.get(url)
    product_el=driver.find_elements_by_xpath("//a[@class='IRpwTa']")
    for i in product_el:
        try:
            product_des.append(i.text)
            driver.execute_script("window.scrollBy(0,document.body.scrollHeight0)")
        except:
            product_des.append("--")
        
    return product_des

In [58]:
print(product_des)

NameError: name 'product_des' is not defined

In [53]:
def scrape_price(url):
    price=[]
    driver.get(url)
    price_el=driver.find_elements_by_xpath("//div[@class='_30jeq3']")
    
    for i in price_el:
        try:
            price.append(i.text)
            driver.execute_script("window.scrollBy(0,document.body.scrollHeight0)")
            
        except:
            price.append("--")
        
    return price

In [54]:
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [56]:
print(price)

['SRPM']

In [55]:
brand_list=[]
product_list=[]
price_list=[]
urls='=sunglasses&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page='
for i in ['1','2','3']:

   url= urls+i
   time.sleep(5)
   brand=scrape_brand_name(url)
   brand_list.extend(brand) 
   product=scrape_product_des(url)
   product_list.extend(product)
   price=scrape_price(url)
   price_list.extend(price)

NameError: name 'StaleElementReferenceException' is not defined

In [ ]:
length=[len(brand_list),len(product_list),len(price_list)]
length

In [57]:
#creating DataFrame for the scraped Data
import pandas as pd
df5=pd.DataFrame()
df5["BRAND"]=brand_list[:100]
df5["PRODUCT_DESCRIPTION"]=product_list[:100]
df5["PRICE"]=price_list[:100]
df5

Empty DataFrame
Columns: [BRAND, PRODUCT_DESCRIPTION, PRICE]
Index: []

In [47]:
glasses = driver.find_elements(By.XPATH,"//div[@id='container']/div/div[3]/div/div[2]/div[2]/div/div/div/div/a")

glasses[0:100]

[<selenium.webdriver.remote.webelement.WebElement (session="5ccdab69f1b34ed58be3ee91a650b095", element="545D59A54E574A78C2CA3CC2BB1007B9_element_257")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ccdab69f1b34ed58be3ee91a650b095", element="545D59A54E574A78C2CA3CC2BB1007B9_element_258")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ccdab69f1b34ed58be3ee91a650b095", element="545D59A54E574A78C2CA3CC2BB1007B9_element_259")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ccdab69f1b34ed58be3ee91a650b095", element="545D59A54E574A78C2CA3CC2BB1007B9_element_260")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ccdab69f1b34ed58be3ee91a650b095", element="545D59A54E574A78C2CA3CC2BB1007B9_element_261")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ccdab69f1b34ed58be3ee91a650b095", element="545D59A54E574A78C2CA3CC2BB1007B9_element_262")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ccdab69f1b34ed58be3ee91a650b095", element="545D59A54E574A78C2CA3CC2BB1007B9_element_263")>,
 <selenium.webdriver.remote.webelement.WebElement (session="5ccdab69f1b34ed58be3ee91a650b095", element="545D59A54E574A78C2CA3CC2BB1007B9_element_264")>]

In [48]:
product = []

for i in glasses[0:40]:
    product.append(i.text)
product

['UV Protection, Polarized Over-sized Sunglasses (50)',
 '₹899₹1,99955% off\nFree delivery',
 'Riding Glasses, UV Protection Clubmaster, Wayfarer Sung...',
 '₹379₹1,99981% off\nFree delivery',
 'UV Protection Wayfarer Sunglasses (50)',
 '₹204₹1,29984% off\nFree delivery by Today',
 'UV Protection Clubmaster Sunglasses (54)',
 '₹239₹1,59985% off\nFree delivery by Today']

In [33]:
print(len(glasses))

8

In [24]:
# Extract job title 

title = driver.find_elements(By.CLASS_NAME,"_2r_T1I")

for i in title[0:40]:
    
    titles=i.text
    product.append(titles)

In [25]:
print(product)

['UV Protection, Polarized Over-sized Sunglasses (50)', '₹899₹1,99955% off\nFree delivery', 'Riding Glasses, UV Protection Clubmaster, Wayfarer Sung...', '₹379₹1,99981% off\nFree delivery', 'UV Protection Wayfarer Sunglasses (50)', '₹204₹1,29984% off\nFree delivery by Today', 'UV Protection Clubmaster Sunglasses (54)', '₹239₹1,59985% off\nFree delivery by Today', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

In [26]:
print(len(product))

48

In [81]:
# Creating Dataframe

df = pd.DataFrame({'Product':product})
df

                                              Product
0   Riding Glasses, UV Protection Clubmaster, Wayf...
1                    ₹379₹1,99981% off\nFree delivery
2           UV Protection Rectangular Sunglasses (55)
3                    ₹502₹1,99974% off\nFree delivery
4              UV Protection Wayfarer Sunglasses (50)
5           ₹204₹1,29984% off\nFree delivery by Today
6            UV Protection Clubmaster Sunglasses (54)
7           ₹239₹1,59985% off\nFree delivery by Today
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
..                                                ...
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87

[88 rows x 1 columns]

# Question 5

In [66]:
driver = webdriver.Chrome()

In [67]:
url='https://www.flipkart.com/apple-iphone-11-black-64-gb/product-reviews/itm4e5041ba101fd?pid=MOBFWQ6BXGJCEYNY&lid=LSTMOBFWQ6BXGJCEYNYZXSHRJ&market'
driver.get(url)

In [68]:
driver.maximize_window()

In [84]:
rating_el=driver.find_elements(By.XPATH,"//div[@class='_3LWZlK _1BLPMq']")
Rating=[]
for i in rating_el:
    Rating.append(i.text)
Rating

['5', '5', '5', '5', '5', '5', '5', '5', '5', '5']

In [91]:
review_sum=driver.find_elements(By.XPATH,"//p[@class='_2-N8zT']")
Review=[]
for i in review_sum:
    Review.append(i.text)
Review

['Classy product',
 'Classy product',
 'Terrific',
 'Wonderful',
 'Perfect product!',
 'Worth every penny',
 'Best in the market!',
 'Just wow!',
 'Fabulous!',
 'Great product']

In [94]:
full_review=driver.find_elements(By.XPATH,"//div[@class='t-ZTKy']")
Full_Review=[]
for i in full_review:
    Full_Review.append(i.text)
Full_Review

['Photos super',
 'Camera is awesome\nBest battery backup\nA performer 👌🏻\nIt will be a real value for money if they provide charger and earphone inbox!',
 'Very very good',
 'This is amazing at all',
 'V Good all',
 'Feeling awesome after getting the delivery of my phone. Dual speakers makes the sound quality very loud. Amazing!!',
 'Good Camera',
 'Perfect Product!!',
 'Super🔥 and good performance 👌❤️',
 'Purple is best']

In [95]:
#inspecting the length of scraped attributes

length_list=[len(Rating),len(Review),len(Full_Review)]
length_list

[10, 10, 10]

In [99]:
#creating DataFrame for the scraped data

import pandas as pd

iphone=pd.DataFrame()
iphone["INDEX"]=range(1,11)
iphone["RATING"]=Rating[:10]
iphone["REVIEW"]=Review[:10]
iphone["FULL REVIEW"]=Full_Review[:10]
iphone.set_index("INDEX",inplace=True)
iphone

,RATING,REVIEW,FULL REVIEW
INDEX,,,
1,5,Classy product,Photos super
2,5,Classy product,Camera is awesome\nBest battery backup\nA perf...
3,5,Terrific,Very very good
4,5,Wonderful,This is amazing at all
5,5,Perfect product!,V Good all
6,5,Worth every penny,Feeling awesome after getting the delivery of ...
7,5,Best in the market!,Good Camera
8,5,Just wow!,Perfect Product!!
9,5,Fabulous!,Super🔥 and good performance 👌❤️
10,5,Great product,Purple is best

# Question 6

In [9]:
driver = webdriver.Chrome()

In [10]:
url='https://www.flipkart.com/'
driver.get(url)

In [13]:
search=driver.find_element(By.XPATH,"//input[@class='Pke_EE']")

In [14]:
search.send_keys("sneakers")

In [17]:
btn=driver.find_element(By.XPATH,"//button[@class='_2iLD__']")

In [18]:
btn.click()

In [19]:
#creating functions to scrape data
import time

In [50]:
def scrape_brand():
    brand=[]
    brand_el=driver.find_elements(By.XPATH,"//div[@class='_2WkVRV']")
    time.sleep(3)
    for i in brand_el:
        try:
            brand.append(i.text)
            driver.execute_script("window.scrollBy(0,document.body.scrollHeight0)")
        except:
            brand.append("--")
    return brand

In [51]:
print(brand)

['SFR', 'SFR', 'Nobelite', 'BRUTON', 'PUMA', 'PUMA', 'Free Kicks', 'K- FOOTLANCE', 'aadi', 'PUMA', 'WHITE WALKERS', 'WHITE WALKERS', 'Asics', 'PUMA', 'Sparx', 'Sparx', 'SFR', 'SFR', 'Free Kicks', 'Nobelite', 'Free Kicks', 'RapidBox', 'Layasa', 'PUMA', 'asian', 'asian', 'Free Kicks', 'Krors', 'PUMA', 'PUMA', 'ATOM', 'RapidBox', 'Kraasa', 'aadi', 'Free Kicks', 'Airson', 'ATOM', 'Fastnslow', 'PUMA', 'BRUTON']

In [52]:
def scrape_description():
    description=[]
    des_el=driver.find_elements(By.XPATH,"//a[@class='IRpwTa' or @class='IRpwTa _2-ICcC']")
    print(len(des_el))
    time.sleep(3)
    for i in des_el:
        try:
            description.append(i.text)
            driver.execute_script("window.scrollBy(0,document.body.scrollHeight0)")
        except:
            description.append("--")
    return description

In [53]:
print(description)

['Exclusive Affordable Collection of Trendy & Stylish Sne...', 'Sneakers For Men', 'Sneakers For Men', 'Modern Trendy Shoes Sneakers For Men', 'Puma Rebound LayUp SL Sneakers For Men', 'Buzz Sneakers For Men', 'Sneakers For Men', 'Black Outdoor Gym,Sports,Training,Stylish Running Shoes...', 'Lightweight,Comfort,Summer,Trendy,Walking,Outdoor,Styli...', 'Rebound LayUp SL Sneakers For Men', 'Stylish & Trending Outdoor Walking Comfortable Sneakers...', 'Stylish & Trending Outdoor Walking Comfortable Sneakers...', 'fuzor B Sneakers For Men', 'Hustle V2 Sneakers For Men', 'Canvas Casual Partywear Outdoor Sneakers Shoes For Mens...', 'Sneakers For Men', 'Exclusive Affordable Collection of Trendy & Stylish Sne...', 'Exclusive Affordable Collection of Trendy & Stylish Sne...', 'Combo Of 2 Shoes FK-570 & FK-492 Sneakers For Men', 'Sneakers For Men', 'FK-201 Lightweight Sneakers For Men', 'Sneakers For Men', 'Sneakers For Men', 'UP Sneakers For Men', 'Sneakers For Men', 'Trendy-21 White Color Change Sneakers,Casuals,Loafers S...', 'FK-Fusion Sports Stylish Sneakers For Men', 'Premium Ankle Length Black Denim Boots Sneakers For Men', 'Caven Sneakers For Men', 'Hustle V2 Sneakers For Men', 'Sneakers For Men', 'Sneakers For Men', 'INFINITY 2.0 Sneakers For Women', 'Sneakers For Men', 'Sneakers For Men', 'Junior Zero1 Sports shoes for Men | Gym Training Walkin...', 'Sneakers For Men', 'sports Sneakers For Men', 'UP Sneakers For Men', 'Exclusive Sneaker Shoes Sneakers For Men']

In [48]:
def scrape_price():
    price=[]
    price_el=driver.find_elements(By.XPATH,"//div[@class='_30jeq3']")
    time.sleep(3)
    for i in price_el:
        try:
            price.append(i.text)
            driver.execute_script("window.scrollBy(0,document.body.scrollHeight0)")
        except:
            price.append("--")
            
    return price

In [49]:
print(price)

['₹349', '₹299', '₹299', '₹379', '₹1,930', '₹3,599', '₹599', '₹499', '₹299', '₹2,649', '₹599', '₹599', '₹2,139', '₹1,299', '₹584', '₹562', '₹349', '₹349', '₹1,400', '₹299', '₹299', '₹695', '₹399', '₹1,508', '₹622', '₹649', '₹429', '₹457', '₹2,079', '₹1,299', '₹1,485', '₹750', '₹399', '₹435', '₹1,400', '₹999', '₹1,485', '₹549', '₹1,552', '₹349']

In [57]:
brand=[]
description=[]
price=[]
next_btn=[]
length=len(brand)
while(length<=100):
    driver.refresh()
    brand.extend(scrape_brand())
    description.extend(scrape_description())
    price.extend(scrape_price())
    
    time.sleep(3)
    next_btn=driver.find_elements(By.XPATH,"//a[@class='_22Tduf']/span")
    #next_btn.click()
    length=len(brand)
len(brand)    
len(price)

40
40
40

120

In [58]:
#inspecting the length of scraped attributes
length_list=[len(brand),len(description),len(price)]
length_list

[120, 120, 120]

In [60]:
#creating DataFrame for the scraped data

import pandas as pd

sneakers=pd.DataFrame()
sneakers["INDEX"]=range(1,101)
sneakers["BRAND"]=brand[:100]
sneakers["PRODUCT_DESCRIPTION"]=description[:100]
sneakers["PRICE"]=price[:100]
sneakers.set_index("INDEX",inplace=True)
sneakers

,BRAND,PRODUCT_DESCRIPTION,PRICE
INDEX,,,
1,SFR,Exclusive Affordable Collection of Trendy & St...,₹349
2,SFR,Sneakers For Men,₹299
3,Nobelite,Sneakers For Men,₹299
4,BRUTON,Modern Trendy Shoes Sneakers For Men,₹379
5,PUMA,Puma Rebound LayUp SL Sneakers For Men,"₹1,930"
6,PUMA,Buzz Sneakers For Men,"₹3,599"
7,Free Kicks,Sneakers For Men,₹599
8,K- FOOTLANCE,"Black Outdoor Gym,Sports,Training,Stylish Runn...",₹499
9,aadi,"Lightweight,Comfort,Summer,Trendy,Walking,Outd...",₹299
10,PUMA,Rebound LayUp SL Sneakers For Men,"₹2,649"
11,WHITE WALKERS,Stylish & Trending Outdoor Walking Comfortable...,₹599
12,WHITE WALKERS,Stylish & Trending Outdoor Walking Comfortable...,₹599
13,Asics,fuzor B Sneakers For Men,"₹1,699"
14,PUMA,Hustle V2 Sneakers For Men,"₹1,299"
15,Sparx,Canvas Casual Partywear Outdoor Sneakers Shoes...,₹584
16,Sparx,Sneakers For Men,₹562
17,SFR,Exclusive Affordable Collection of Trendy & St...,₹349
18,SFR,Exclusive Affordable Collection of Trendy & St...,₹349
19,Free Kicks,Combo Of 2 Shoes FK-570 & FK-492 Sneakers For Men,"₹1,400"
20,Nobelite,Sneakers For Men,₹299
21,Free Kicks,FK-201 Lightweight Sneakers For Men,₹299
22,Free Kicks,FK-Fusion Sports Stylish Sneakers For Men,₹429
23,Layasa,Sneakers For Men,₹399
24,PUMA,UP Sneakers For Men,"₹1,508"
25,asian,Sneakers For Men,₹622
26,asian,"Trendy-21 White Color Change Sneakers,Casuals,...",₹649
27,RapidBox,Sneakers For Men,₹695
28,Krors,Premium Ankle Length Black Denim Boots Sneaker...,₹457
29,PUMA,Caven Sneakers For Men,"₹2,079"
30,PUMA,Hustle V2 Sneakers For Men,"₹1,299"
...,...,...,...
71,ATOM,Sneakers For Men,"₹1,485"
72,Fastnslow,sports Sneakers For Men,₹549
73,Kraasa,INFINITY 2.0 Sneakers For Women,₹399
74,aadi,Sneakers For Men,₹435
75,Free Kicks,Sneakers For Men,"₹1,400"
76,Airson,Junior Zero1 Sports shoes for Men | Gym Traini...,₹999
77,ATOM,Sneakers For Men,"₹1,485"
78,RapidBox,Sneakers For Men,₹750
79,PUMA,UP Sneakers For Men,"₹1,552"
80,BRUTON,Exclusive Sneaker Shoes Sneakers For Men,₹349
81,SFR,Exclusive Affordable Collection of Trendy & St...,₹349
82,SFR,Sneakers For Men,₹299
83,Nobelite,Sneakers For Men,₹299
84,BRUTON,Modern Trendy Shoes Sneakers For Men,₹379
85,PUMA,Puma Rebound LayUp SL Sneakers For Men,"₹1,930"
86,PUMA,Buzz Sneakers For Men,"₹3,599"
87,Free Kicks,Sneakers For Men,₹599
88,K- FOOTLANCE,"Black Outdoor Gym,Sports,Training,Stylish Runn...",₹499
89,aadi,"Lightweight,Comfort,Summer,Trendy,Walking,Outd...",₹299
90,PUMA,Rebound LayUp SL Sneakers For Men,"₹2,649"
91,WHITE WALKERS,Stylish & Trending Outdoor Walking Comfortable...,₹599
92,WHITE WALKERS,Stylish & Trending Outdoor Walking Comfortable...,₹599
93,Asics,fuzor B Sneakers For Men,"₹1,699"
94,PUMA,Hustle V2 Sneakers For Men,"₹1,299"
95,Sparx,Canvas Casual Partywear Outdoor Sneakers Shoes...,₹584
96,Sparx,Sneakers For Men,₹562
97,SFR,Exclusive Affordable Collection of Trendy & St...,₹349
98,SFR,Exclusive Affordable Collection of Trendy & St...,₹349
99,Free Kicks,Combo Of 2 Shoes FK-570 & FK-492 Sneakers For Men,"₹1,400"
100,Nobelite,Sneakers For Men,₹299

# Question 7

In [100]:
driver = webdriver.Chrome()

In [101]:
url="https://www.amazon.in/"
driver.get(url)

In [102]:
driver.maximize_window()

In [103]:
search_col=driver.find_element(By.XPATH,"//input[@class='nav-input nav-progressive-attribute']")
search_col.send_keys('laptop')

In [104]:
search_button=driver.find_elements(By.XPATH,"//input[@class='nav-input nav-progressive-attribute']")

In [105]:
search_button[1].click()

In [106]:
# filter I7 laptop
i7=[]
i7 = driver.find_elements(By.XPATH,"//span[@class='a-size-base a-color-base']")

In [112]:
i7 = driver.find_elements(By.XPATH,"//div[@class='a-checkbox a-checkbox-fancy s-navigation-checkbox aok-float-left']")

In [113]:
i7[2].click()

In [115]:
title_el=driver.find_elements(By.XPATH,"//h2[@class='a-size-mini a-spacing-none a-color-base s-line-clamp-2']")
title=[]
for i in title_el[:10]:
    title.append(i.text)
title

['(Renewed) HP Chromebook Pro 10th Gen Intel Core i5 14" (35.6 cm) FHD Touchscreen Thin & Light Laptop (8 GB DDR4 RAM, 64GB eMMC + 32GB MicroSD Card, Chrome OS, UHD Graphics, WiFi, BT, Webcam)',
 'JioBook 11 (2023) NB1112MM(BLU) (Mediatek 8788 Octa-core 2 GHz/ARM Mali G72 MP3 @800 MHz/29.5cms 60 Hz/Thin and Light Laptop/ 4 GB LPDDR4/ 64 GB eMMC/JioOS 4G LTE, Dual Band Wi-Fi/Blue/ 990 GMS)',
 'Acer Aspire Lite 11th Gen Intel Core i3 Premium Metal Laptop (8GB RAM/512GB SSD/Windows 11 Home) AL15-51, 39.62cm (15.6") Full HD Display, Metal Body, Steel Gray, 1.59 Kg',
 'HP 14s, 11th Gen Intel Core i3-1115G4, 8GB RAM/256GB SSD 14-inch(35.6 cm) Micro-Edge, Anti-Glare, FHD Laptop/Alexa Built-in/Win 11/Intel UHD Graphics/Dual Speakers/MSO 2021/1.41 Kg, 14s-dy2507TU',
 'Acer Aspire Lite 11th Gen Intel Core i5-1155G7 Thin and Light Laptop (16GB RAM/512GB SSD/Intel Iris Xe Graphics, Win 11 Home) AL15-51, 39.62cm (15.6") Full HD Display, Metal Body, Steel Gray, 1.59 Kg',
 'HP Laptop 15s, 11th Gen Intel Core i5-1155G7, 15.6-inch (39.6 cm), FHD, 16GB DDR4, 512GB SSD, Intel Iris Xe Graphics, Backlit KB, Thin & Light (Win 11, MSO 2021, Silver, 1.69 kg), fr4001TU',
 'HP Laptop 15s, Intel Celeron N4500, 15.6 inch(39.6cm) HD Laptop (8GB RAM,512GB SSD,Intel UHD Graphics,Dual Speakers,Numeric Keypad,Alexa,Win 11,MSO 21,Natural Silver,1.69 Kgs) 15s-fq3071TU',
 'Acer Aspire Lite 11th Gen Intel Core i3-1115G4 Premium Thin & Light Laptop (8GB RAM/256GB SSD/Intel UHD Graphics/Win 11 Home) AL15-51, 39.62cm (15.6") Full HD Display, Metal Body, Steel Grey, 1.59 KG',
 "Chuwi HeroBook Pro 14.1'' Laptop, 8GB RAM 256GB SSD, Windows 11 Laptop, 1TB SSD Expand, Intel Celeron N4020(up to 2.8GHz), FHD IPS Display, Ultra Slim, Mini-HDMI, 5G WiFi, USB3.0, Webcam,TF Card",
 'HP Chromebook 15a Intel Celeron N4500 15.6 inch (39.6cm) HD,Anti-Glare, Micro-Edge Laptop(4GB RAM/128 GB eMMC/Intel UHD Graphics/Google Assistant/Chrome 64/Numeric Keypad/Dual Speaker) 15a- na0012TU']

In [116]:
price_el=driver.find_elements(By.XPATH,"//span[@class='a-price-whole']")
price=[]
for i in price_el[:10]:
    price.append(i.text)
price

['19,999',
 '16,499',
 '31,999',
 '35,990',
 '41,990',
 '54,775',
 '28,990',
 '30,999',
 '19,990',
 '17,990']

In [112]:
import time
rating=[]
for i in rating_url[:10]:
    driver.get(i)
    time.sleep(3)
    try:
        
        ratings = driver.find_element(By.XPATH,".//span[@class='a-icon-alt']/..")
        ratings = ratings.get_attribute('innerHTML').split(">")[1].split(" ")[0]
        rating.append(ratings)
    except:
        
        
        rating.append("00")
rating

WebDriverException: Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=116.0.5845.111)
Stacktrace:
	GetHandleVerifier [0x00007FF65D8F52A2+57122]
	(No symbol) [0x00007FF65D86EA92]
	(No symbol) [0x00007FF65D73E3AB]
	(No symbol) [0x00007FF65D72BA47]
	(No symbol) [0x00007FF65D72B6C0]
	(No symbol) [0x00007FF65D73FA71]
	(No symbol) [0x00007FF65D7AE27F]
	(No symbol) [0x00007FF65D796DB3]
	(No symbol) [0x00007FF65D76D2B1]
	(No symbol) [0x00007FF65D76E494]
	GetHandleVerifier [0x00007FF65DB9EF82+2849794]
	GetHandleVerifier [0x00007FF65DBF1D24+3189156]
	GetHandleVerifier [0x00007FF65DBEACAF+3160367]
	GetHandleVerifier [0x00007FF65D986D06+653702]
	(No symbol) [0x00007FF65D87A208]
	(No symbol) [0x00007FF65D8762C4]
	(No symbol) [0x00007FF65D8763F6]
	(No symbol) [0x00007FF65D8667A3]
	BaseThreadInitThunk [0x00007FF882367614+20]
	RtlUserThreadStart [0x00007FF8843426B1+33]

In [113]:
len(price)

10

In [114]:
len(title)

10

In [116]:
#creating DataFrame for the scraped data
import pandas as pd
laptop_df=pd.DataFrame()
laptop_df['INDEX']=range(1,11)
laptop_df['TITLE']=title[:10]
#laptop_df['RATING']=rating[:10]
laptop_df['PRICE']=price[:10]
laptop_df.set_index('INDEX',inplace=True)
laptop_df

                                                   TITLE   PRICE
INDEX
1      Acer Aspire Lite 11th Gen Intel Core i5-1155G7...  50,999
2      Acer Aspire 5 Gaming Laptop Intel Core i5 12th...  52,990
3      (Renewed) HP Chromebook Pro 10th Gen Intel Cor...  37,056
4      JioBook 11 (2023) NB1112MM(BLU) (Mediatek 8788...  41,990
5      Acer Aspire Lite 11th Gen Intel Core i3 Premiu...  54,990
6      HP Laptop 15s, 11th Gen Intel Core i5-1155G7, ...  19,999
7      HP 14s, 11th Gen Intel Core i3-1115G4, 8GB RAM...  16,499
8      HP Laptop 15s, Intel Celeron N4500, 15.6 inch(...  31,999
9      HP Chromebook 15a Intel Celeron N4500 15.6 inc...  58,990
10     ASUS Vivobook 15, Intel Core i7-12650H 12th Ge...  54,775

# Question 8

In [123]:
driver = webdriver.Chrome()

In [124]:
driver.get("https://www.azquotes.com/")

In [128]:
top = driver.find_element(By.XPATH,"//*[@id='menu']/div/div[3]/ul/li[5]/a")

In [129]:
top.click()

In [131]:
quotes=driver.find_elements(By.XPATH,"//a[@class='title']")
Quotes=[]
for i in quotes[:100]:
    Quotes.append(i.text)
Quotes

['The essence of strategy is choosing what not to do.',
 'One cannot and must not try to erase the past merely because it does not fit the present.',
 'Patriotism means to stand by the country. It does not mean to stand by the president.',
 'Death is something inevitable. When a man has done what he considers to be his duty to his people and his country, he can rest in peace. I believe I have made that effort and that is, therefore, why I will sleep for the eternity.',
 'You have to love a nation that celebrates its independence every July 4, not with a parade of guns, tanks, and soldiers who file by the White House in a show of strength and muscle, but with family picnics where kids throw Frisbees, the potato salad gets iffy, and the flies die from happiness. You may think you have overeaten, but it is patriotism.',
 'Be more concerned with your character than your reputation, because your character is what you really are, while your reputation is merely what others think you are.',
 'Weak people revenge. Strong people forgive. Intelligent People Ignore.',
 "A mind is like a parachute. It doesn't work if it is not open.",
 'Never be afraid to raise your voice for honesty and truth and compassion against injustice and lying and greed. If people all over the world...would do this, it would change the earth.',
 'There are three kinds of men. The one that learns by reading. The few who learn by observation. The rest of them have to pee on the electric fence for themselves.',
 "A strong nation, like a strong person, can afford to be gentle, firm, thoughtful, and restrained. It can afford to extend a helping hand to others. It's a weak nation, like a weak person, that must behave with bluster and boasting and rashness and other signs of insecurity.",
 'The difference between stupidity and genius is that genius has its limits.',
 'We the people are the rightful masters of both Congress and the courts, not to overthrow the Constitution but to overthrow the men who pervert the Constitution.',
 'With or without religion, you would have good people doing good things and evil people doing evil things. But for good people to do evil things, that takes religion.',
 'Human kindness has never weakened the stamina or softened the fiber of a free people. A nation does not have to be cruel to be tough.',
 'A person who never made a mistake never tried anything new.',
 'My mission in life is not merely to survive, but to thrive; and to do so with some passion, some compassion, some humor, and some style',
 'Life is short, Break the Rules. Forgive quickly, Kiss slowly. Love truly. Laugh uncontrollably And never regret ANYTHING That makes you smile.',
 'This country will not be a good place for any of us to live in unless we make it a good place for all of us to live in.',
 'In a world filled with hate, we must still dare to hope. In a world filled with anger, we must still dare to comfort. In a world filled with despair, we must still dare to dream. And in a world filled with distrust, we must still dare to believe.',
 'Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.',
 'To be a Christian means to forgive the inexcusable because God has forgiven the inexcusable in you.',
 'A man who is good enough to shed his blood for the country is good enough to be given a square deal afterwards.',
 'Kindness is the language which the deaf can hear and the blind can see.',
 'Most folks are as happy as they make up their minds to be.',
 'A happy marriage is the union of two good forgivers.',
 'I believe in Christianity as I believe that the sun has risen: not only because I see it, but because by it I see everything else.',
 'Politics is the art of looking for trouble, finding it everywhere, diagnosing it incorrectly and applying the wrong remedies.',
 "I believe in everything until it's disproved. So I believe in fairies, the myths, dragons. It all exists, even if it's in your mind. Who's to say that dreams and nightmares aren't as real as the here and now?",
 'At the end of your life, you will never regret not having passed one more test, not winning one more verdict or not closing one more deal. You will regret time not spent with a husband, a friend, a child, or a parent.',
 'I never think of the future - it comes soon enough.',
 "Our greatest fear should not be of failure but of succeeding at things in life that don't really matter.",
 'Failure is simply the opportunity to begin again, this time more intelligently.',
 'Music expresses that which cannot be put into words.',
 'Good actions are a guard against the blows of adversity.',
 'Positive thinking will let you do everything better than negative thinking will.',
 "You have enemies? Good. That means you've stood up for something, sometime in your life.",
 "You don't have to be great to start, but you have to start to be great",
 'Let every nation know, whether it wishes us well or ill, that we shall pay any price, bear any burden, meet any hardship, support any friend, oppose any foe to assure the survival and the success of liberty.',
 "If you want total security, go to prison. There you're fed, clothed, given medical care and so on. The only thing lacking... is freedom.",
 'Socialism is a philosophy of failure, the creed of ignorance, and the gospel of envy, its inherent virtue is the equal sharing of misery.',
 'It is the supreme art of the teacher to awaken joy in creative expression and knowledge.',
 "Once you replace negative thoughts with positive ones, you'll start having positive results.",
 "You build on failure. You use it as a stepping stone. Close the door on the past. You don't try to forget the mistakes, but you don't dwell on it. You don't let it have any of your energy, or any of your time, or any of your space.",
 'All my life through, the new sights of Nature made me rejoice like a child.',
 "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
 'Marriage is not a ritual or an end. It is a long, intricate, intimate dance together and nothing matters more than your own sense of balance and your choice of partner.',
 'When obstacles arise, you change your direction to reach your goal; you do not change your decision to get there.',
 'Time you enjoy wasting, was not wasted.',
 'The next time some academics tell you how important diversity is, ask how many Republicans there are in their sociology department.',
 'Faith is not the belief that God will do what you want. It is the belief that God will do what is right.',
 "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.",
 'It is hard to imagine a more stupid or more dangerous way of making decisions than by putting those decisions in the hands of people who pay no price for being wrong.',
 'I say that the most liberating thing about beauty is realizing that you are the beholder.',
 'The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy.',
 'The soldier, above all other people, prays for peace, for he must suffer and bear the deepest wounds and scars of war.',
 'A true leader has the confidence to stand alone, the courage to make tough decisions, and the compassion to listen to the needs of others. He does not set out to be a leader, but becomes one by the equality of his actions and the integrity of his intent.',
 'I am a Soldier, I fight where I am told, and I win where I fight.',
 "Trying to do the Lord's work in your own strength is the most confusing, exhausting, and tedious of all work. But when you are filled with the Holy Spirit, then the ministry of Jesus just flows out of you.",
 "Sports for me is when a guy walks off the court, and you really can't tell whether he won or lost, when he carries himself with pride either way.",
 'Expect the best. Prepare for the worst. Capitalize on what comes.',
 'I became insane, with long intervals of horrible sanity.',
 'Failure is a detour, not a dead-end street.',
 'I am not a product of my circumstances. I am a product of my decisions.',
 'You can cut all the flowers but you cannot keep spring from coming.',
 "Life doesn't run away from nobody. Life runs at people.",
 'In order to succeed, your desire for success should be greater than your fear of failure.',
 "It's difficult to think anything but pleasant thoughts while eating a homegrown tomato.",
 'Too many of us are not living our dreams because we are living our fears.',
 'If the only prayer you ever say in your entire life is thank you, it will be enough.',
 "It's just a job. Grass grows, birds fly, waves pound the sand. I beat people up.",
 'A man must be big enough to admit his mistakes, smart enough to profit from them, and strong enough to correct them.',
 'Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.',
 'This is one small step for a man, one giant leap for mankind.',
 "It has been said, 'time heals all wounds.' I do not agree. The wounds remain. In time, the mind, protecting its sanity, covers them with scar tissue and the pain lessens. But it is never gone.",
 "I have held many things in my hands, and I have lost them all; but whatever I have placed in God's hands, that I still possess.",
 "Welfare's purpose should be to eliminate, as far as possible, the need for its own existence.",
 'Each time, before you intercede, be quiet first, and worship God in His glory. Think of what He can do, and how He delights to hear the prayers of His redeemed people. Think of your place and privilege in Christ, and expect great things!',
 "Failure is not the opposite of success; it's part of success.",
 'No one has ever become poor by giving.',
 'It is not my ability, but my response to God’s ability, that counts.',
 'No one is born hating another person because of the color of his skin, or his background, or his religion. People must learn to hate, and if they can learn to hate, they can be taught to love, for love comes more naturally to the human heart than its opposite.',
 'No matter what people tell you, words and ideas can change the world.',
 'A man should never neglect his family for business.',
 'Those who dare to fail miserably can achieve greatly.',
 'The two most important days in your life are the day you are born and the day you find out why.',
 'We must be global Christians with a global vision because our God is a global God.',
 'With everything that has happened to you, you can either feel sorry for yourself or treat what has happened as a gift. Everything is either an opportunity to grow or an obstacle to keep you from growing. You get to choose.',
 'Don’t let the noise of others’ opinions drown out your own inner voice.',
 'History, despite its wrenching pain, cannot be unlived, but if faced with courage, need not be lived again.',
 "How old would you be if you didn't know how old you are?",
 'Leadership is a privilege to better the lives of others. It is not an opportunity to satisfy personal greed.',
 'If you have good thoughts they will shine out of your face like sunbeams and you will always look lovely.',
 'Never cut a tree down in the wintertime. Never make a negative decision in the low time. Never make your most important decisions when you are in your worst moods. Wait. Be patient. The storm will pass. The spring will come.',
 'An optimist stays up until midnight to see the new year in. A pessimist stays up to make sure the old year leaves.',
 'When the going gets weird, the weird turn pro.',
 "When a train goes through a tunnel and it gets dark, you don't throw away the ticket and jump off. You sit still and trust the engineer.",
 'If you think you are too small to make a difference, try sleeping with a mosquito.',
 "God doesn't require us to succeed, he only requires that you try.",
 'Change your thoughts and you change your world.']

In [133]:
Author_quote=driver.find_elements(By.XPATH,"//div[@class='author']")
Author=[]
for i in Author_quote[:100]:
    Author.append(i.text)
Author

['Michael Porter',
 'Golda Meir',
 'Theodore Roosevelt',
 'Nelson Mandela',
 'Erma Bombeck',
 'John Wooden',
 'Albert Einstein',
 'Frank Zappa',
 'William Faulkner',
 'Will Rogers',
 'Jimmy Carter',
 'Albert Einstein',
 'Abraham Lincoln',
 'Steven Weinberg',
 'Franklin D. Roosevelt',
 'Albert Einstein',
 'Maya Angelou',
 'Mark Twain',
 'Theodore Roosevelt',
 'Michael Jackson',
 'Martin Luther King, Jr.',
 'C. S. Lewis',
 'Theodore Roosevelt',
 'Mark Twain',
 'Abraham Lincoln',
 'Ruth Graham',
 'C. S. Lewis',
 'Groucho Marx',
 'John Lennon',
 'Barbara Bush',
 'Albert Einstein',
 'Francis Chan',
 'Henry Ford',
 'Victor Hugo',
 'Abu Bakr',
 'Zig Ziglar',
 'Winston Churchill',
 'Zig Ziglar',
 'John F. Kennedy',
 'Dwight D. Eisenhower',
 'Winston Churchill',
 'Albert Einstein',
 'Willie Nelson',
 'Johnny Cash',
 'Marie Curie',
 'Maya Angelou',
 'Amy Bloom',
 'Zig Ziglar',
 'John Lennon',
 'Thomas Sowell',
 'Max Lucado',
 'Martin Luther King, Jr.',
 'Thomas Sowell',
 'Salma Hayek',
 'Martin Luther King, Jr.',
 'Douglas MacArthur',
 'Douglas MacArthur',
 'George S. Patton',
 'Corrie Ten Boom',
 'Jim Courier',
 'Zig Ziglar',
 'Edgar Allan Poe',
 'Zig Ziglar',
 'Stephen Covey',
 'Pablo Neruda',
 'Joe Frazier',
 'Bill Cosby',
 'Lewis Grizzard',
 'Les Brown',
 'Meister Eckhart',
 'Muhammad Ali',
 'John C. Maxwell',
 'Thomas A. Edison',
 'Neil Armstrong',
 'Rose Kennedy',
 'Martin Luther',
 'Ronald Reagan',
 'Andrew Murray',
 'Arianna Huffington',
 'Anne Frank',
 'Corrie Ten Boom',
 'Nelson Mandela',
 'Robin Williams',
 'Walt Disney',
 'John F. Kennedy',
 'Mark Twain',
 'John Stott',
 'Wayne Dyer',
 'Steve Jobs',
 'Maya Angelou',
 'Satchel Paige',
 'Mwai Kibaki',
 'Roald Dahl',
 'Robert H. Schuller',
 'Bill Vaughan',
 'Hunter S. Thompson',
 'Corrie Ten Boom',
 'Dalai Lama',
 'Mother Teresa',
 'Norman Vincent Peale']

In [144]:
types=driver.find_elements(By.XPATH,"//div[@class='tags']")
Types_of_quotes=[]
for i in types[:100]:
    Types_of_quotes.append(i.text)
Types_of_quotes

['Essence, Deep Thought, Transcendentalism',
 'Inspiration, Past, Trying',
 'Country, Peace, War',
 'Inspirational, Motivational, Death',
 '4th Of July, Food, Patriotic',
 'Inspirational, Success, Basketball',
 'Strong, Revenge, Intelligent',
 'Inspirational, Teacher, Religious',
 'Truth, Honesty, Lying',
 'Funny, Reading, Learning',
 'Strong, Thoughtful, Compassion',
 'Love, Funny, Life',
 'Freedom, Men, Democracies Have',
 'God, Religious, Atheist',
 'Respect, Kindness, Character',
 'Inspirational, Motivational, Change',
 'Inspirational, Life, Inspiring',
 'Love, Inspirational, Life',
 'Inspiring, Country, 4th Of July',
 'Inspirational, Dream, Hate',
 'Love, Inspirational, Life',
 'Forgiveness, God, Christian',
 'Country, Men, Squares',
 'Inspirational, Relationship, Positive',
 'Inspirational, Motivational, Positive',
 'Love, Friendship, Relationship',
 'Faith, God, Christian',
 'Art, Freedom, Political Will',
 'Inspirational, Life, Faith',
 'Inspirational, Life, Meaningful',
 'Happiness, Time, Clever',
 'Inspirational, Inspiring, Success',
 'Love, Inspirational, Life',
 'Music, Sound And Music, Musical Life',
 'Adversity, Blow, Action',
 'Positive, Thinking Of You, Attitude',
 'Inspirational, Funny, Life',
 'Inspirational, Life, Motivational',
 'Inspirational, Memorial Day, Freedom',
 'Freedom, Patriotic, Vaccines',
 'Philosophy, Ignorance, Democratic Socialism',
 'Inspirational, Dance, Education',
 'Life, Change, Positive',
 'Life, Bullying, Mistake',
 'Life, Nature, Children',
 'Inspirational, Life, Motivational',
 'Marriage, Love You, Long',
 'Inspirational, Motivational, Success',
 'Love, Inspirational, Life',
 'Diversity, Important, Liberty',
 'Inspirational, God, Faith',
 'Inspirational, Motivational, Inspiring',
 'Business, Stupid, Government',
 'Beauty, Love Yourself, Your Beautiful',
 'Inspirational, Life, Motivational',
 'Peace, Military, War',
 'Inspirational, Leadership, Confidence',
 'Motivational, Military, War',
 'Christian, Jesus, Confusing',
 'Inspirational, Success, Sports',
 'Inspirational, Motivational, Success',
 'Inspirational, Life, Clever',
 'Inspirational, Death, Failure',
 'Inspirational, Life, Motivational',
 'Inspiring, Hope, Spring',
 'Motivational, Running, People',
 'Inspirational, Motivational, Positive',
 'Summer, Food, Garden',
 'Inspirational, Life, Motivational',
 'Inspirational, Life, Thank You',
 'Funny, Sports, Jobs',
 'Being Strong, Wisdom, Stay Strong',
 'Inspirational, Motivational, Positive',
 'Motivational, Positive, Moon',
 'Time, Pain, Get Well',
 'Life, God, Christian',
 'President, Needs, Purpose',
 'God, Faith, Christian',
 'Women, Failure, Successful',
 'Inspirational, Morning, Kindness',
 'Hiding Place, Ability, Baby Boom',
 'Love, Inspirational, Life',
 'Inspirational, Change, Philosophy',
 'Inspirational, Family, Inspiring',
 'Inspirational, Success, Courage',
 'Inspirational, Life, Motivational',
 'Christian, Vision, Missionary',
 'Inspirational, Positive, Regret',
 'Love, Inspirational, Life',
 'Inspirational, Life, Encouragement',
 'Happy Birthday, Baseball, Fun',
 'Leadership, Power, Opportunity',
 'Inspirational, Life, Positive',
 'Inspirational, Encouraging, Patience',
 'New Year, Fun, New Beginnings',
 'Music, Sports, Hunting',
 'Trust, Encouraging, Uplifting',
 'Inspirational, Funny, Change',
 'Success, God, Mother',
 'Inspirational, Motivational, Change']

In [145]:
print(len(Quotes),len(Author),len(Types_of_quotes))

100 100 100

In [146]:
#creating DataFrame for the scraped data
import pandas as pd
df=pd.DataFrame()
df['INDEX']=range(1,101)
df['Quotes']=Quotes[:100]
df['Author']=Author[:100]
df['Types_of_quotes']=Types_of_quotes[:100]
df.set_index('INDEX',inplace=True)
df

,Quotes,Author,Types_of_quotes
INDEX,,,
1,The essence of strategy is choosing what not t...,Michael Porter,"Essence, Deep Thought, Transcendentalism"
2,One cannot and must not try to erase the past ...,Golda Meir,"Inspiration, Past, Trying"
3,Patriotism means to stand by the country. It d...,Theodore Roosevelt,"Country, Peace, War"
4,Death is something inevitable. When a man has ...,Nelson Mandela,"Inspirational, Motivational, Death"
5,You have to love a nation that celebrates its ...,Erma Bombeck,"4th Of July, Food, Patriotic"
6,Be more concerned with your character than you...,John Wooden,"Inspirational, Success, Basketball"
7,Weak people revenge. Strong people forgive. In...,Albert Einstein,"Strong, Revenge, Intelligent"
8,A mind is like a parachute. It doesn't work if...,Frank Zappa,"Inspirational, Teacher, Religious"
9,Never be afraid to raise your voice for honest...,William Faulkner,"Truth, Honesty, Lying"
10,There are three kinds of men. The one that lea...,Will Rogers,"Funny, Reading, Learning"
11,"A strong nation, like a strong person, can aff...",Jimmy Carter,"Strong, Thoughtful, Compassion"
12,The difference between stupidity and genius is...,Albert Einstein,"Love, Funny, Life"
13,We the people are the rightful masters of both...,Abraham Lincoln,"Freedom, Men, Democracies Have"
14,"With or without religion, you would have good ...",Steven Weinberg,"God, Religious, Atheist"
15,Human kindness has never weakened the stamina ...,Franklin D. Roosevelt,"Respect, Kindness, Character"
16,A person who never made a mistake never tried ...,Albert Einstein,"Inspirational, Motivational, Change"
17,"My mission in life is not merely to survive, b...",Maya Angelou,"Inspirational, Life, Inspiring"
18,"Life is short, Break the Rules. Forgive quickl...",Mark Twain,"Love, Inspirational, Life"
19,This country will not be a good place for any ...,Theodore Roosevelt,"Inspiring, Country, 4th Of July"
20,"In a world filled with hate, we must still dar...",Michael Jackson,"Inspirational, Dream, Hate"
21,Darkness cannot drive out darkness; only light...,"Martin Luther King, Jr.","Love, Inspirational, Life"
22,To be a Christian means to forgive the inexcus...,C. S. Lewis,"Forgiveness, God, Christian"
23,A man who is good enough to shed his blood for...,Theodore Roosevelt,"Country, Men, Squares"
24,Kindness is the language which the deaf can he...,Mark Twain,"Inspirational, Relationship, Positive"
25,Most folks are as happy as they make up their ...,Abraham Lincoln,"Inspirational, Motivational, Positive"
26,A happy marriage is the union of two good forg...,Ruth Graham,"Love, Friendship, Relationship"
27,I believe in Christianity as I believe that th...,C. S. Lewis,"Faith, God, Christian"
28,"Politics is the art of looking for trouble, fi...",Groucho Marx,"Art, Freedom, Political Will"
29,I believe in everything until it's disproved. ...,John Lennon,"Inspirational, Life, Faith"
30,"At the end of your life, you will never regret...",Barbara Bush,"Inspirational, Life, Meaningful"
...,...,...,...
71,"It's just a job. Grass grows, birds fly, waves...",Muhammad Ali,"Funny, Sports, Jobs"
72,A man must be big enough to admit his mistakes...,John C. Maxwell,"Being Strong, Wisdom, Stay Strong"
73,Our greatest weakness lies in giving up. The m...,Thomas A. Edison,"Inspirational, Motivational, Positive"
74,"This is one small step for a man, one giant le...",Neil Armstrong,"Motivational, Positive, Moon"
75,"It has been said, 'time heals all wounds.' I d...",Rose Kennedy,"Time, Pain, Get Well"
76,"I have held many things in my hands, and I hav...",Martin Luther,"Life, God, Christian"
77,"Welfare's purpose should be to eliminate, as f...",Ronald Reagan,"President, Needs, Purpose"
78,"Each time, before you intercede, be quiet firs...",Andrew Murray,"God, Faith, Christian"
79,Failure is not the opposite of success; it's p...,Arianna Huffington,"Women, Failure, Successful"
80,No one has ever become poor by giving.,Anne Frank,"Inspirational, Morning, Kindness"
81,"It is not my ability, but my response to God’s...",Corrie Ten Boom,"Hiding Place, Ability, Baby Boom"
82,No one is born hating another person because o...,Nelson Mandela,"Love, Inspirational, Life"
83,"No matter what people tell you, words and idea...",Robin Williams,"Inspirational, Change, Philosophy"
84,A man should never neglect his family for busi...,Walt Disney,"Inspirational, Family, Inspiring"
85,Those who dare to fail miserably can achieve g...,John F. Kennedy,"Inspirational, Success, Courage"
86,The two most important days in your life are t...,Mark Twain,"Inspirational, Life, Motivational"
87,We must be global Christians with a global vis...,John Stott,"Christian, Vision, Missionary"
88,"With everything that has happened to you, you ...",Wayne Dyer,"Inspirational, Positive, Regret"
89,Don’t let the noise of others’ opinions drown ...,Steve Jobs,"Love, Inspirational, Life"
90,"History, despite its wrenching pain, cannot be...",Maya Angelou,"Inspirational, Life, Encouragement"
91,How old would you be if you didn't know how ol...,Satchel Paige,"Happy Birthday, Baseball, Fun"
92,Leadership is a privilege to better the lives ...,Mwai Kibaki,"Leadership, Power, Opportunity"
93,If you have good thoughts they will shine out ...,Roald Dahl,"Inspirational, Life, Positive"
94,Never cut a tree down in the wintertime. Never...,Robert H. Schuller,"Inspirational, Encouraging, Patience"
95,An optimist stays up until midnight to see the...,Bill Vaughan,"New Year, Fun, New Beginnings"
96,"When the going gets weird, the weird turn pro.",Hunter S. Thompson,"Music, Sports, Hunting"
97,When a train goes through a tunnel and it gets...,Corrie Ten Boom,"Trust, Encouraging, Uplifting"
98,If you think you are too small to make a diffe...,Dalai Lama,"Inspirational, Funny, Change"
99,"God doesn't require us to succeed, he only req...",Mother Teresa,"Success, God, Mother"
100,Change your thoughts and you change your world.,Norman Vincent Peale,"Inspirational, Motivational, Change"

# Question 9

In [144]:
driver = webdriver.Chrome()

In [145]:
url = "https://www.jagranjosh.com/"
driver.get(url)

In [146]:
driver.maximize_window()

In [148]:
gk=driver.find_element(By.XPATH,"//a[contains(text(),'GK')]")

In [149]:
gk.click()

In [151]:
pm=driver.find_element(By.XPATH,"//a[contains(text(),'List of all Prime Ministers of India')]")

In [152]:
pm.click()

In [190]:
pm_name=driver.find_elements(By.XPATH,"//div[@class='table-box']/tbody/tr/th[2]")
Name=[]
for i in pm_name[:19]:
    Name.append(i.text)
Name

[]

In [ ]:
/html/body/div[1]/div[2]/div/div[2]/div/div[1]/div/div/div/div[4]/span/div[2]

In [ ]:
//div[@id='itemdiv']/div[4]/span/div[2]/table/tbody/tr/th[2]/p/strong

In [181]:
pm_name=driver.find_elements(By.XPATH,"//strong")
Name=[]
for i in pm_name[:19]:
    Name.append(i.text)
Name

['List of all Prime Ministers of India:',
 'List of all the Prime Ministers of India from 1947-2023',
 'S.N.',
 'PM Name',
 'Born-Dead',
 'Term of office',
 'Remark',
 '1.',
 'Jawahar Lal Nehru',
 '2.',
 '3.',
 '4. ',
 '5.',
 'Indira Gandhi',
 '6.',
 '7.',
 '8.',
 'Indira Gandhi',
 '9.']

In [188]:
born=driver.find_elements(By.XPATH,"/html/body/div[1]/div[2]/div/div[2]/div/div[1]/div/div/div/div[4]/span/div[2]")
BornDead=[]
for i in born[:19]:
    BornDead.append(i.text)
BornDead

['']

In [183]:
term=driver.find_elements(By.XPATH,"//strong")
Term_of_office=[]
for i in term[:19]:
    Term_of_office.append(i.text)
Term_of_office

['List of all Prime Ministers of India:',
 'List of all the Prime Ministers of India from 1947-2023',
 'S.N.',
 'PM Name',
 'Born-Dead',
 'Term of office',
 'Remark',
 '1.',
 'Jawahar Lal Nehru',
 '2.',
 '3.',
 '4. ',
 '5.',
 'Indira Gandhi',
 '6.',
 '7.',
 '8.',
 'Indira Gandhi',
 '9.']

In [161]:
rem=driver.find_elements(By.XPATH,"//strong")
Remark=[]
for i in rem[:19]:
    Remark.append(i.text)
Remark

['List of all Prime Ministers of India:',
 'List of all the Prime Ministers of India from 1947-2023',
 'S.N.',
 'PM Name',
 'Born-Dead',
 'Term of office',
 'Remark',
 '1.',
 'Jawahar Lal Nehru',
 '2.',
 '3.',
 '4. ',
 '5.',
 'Indira Gandhi',
 '6.',
 '7.',
 '8.',
 'Indira Gandhi',
 '9.']

In [ ]:
car_price=driver.find_elements(By.XPATH,"//strong")
price=[]
for i in car_price[:50]:
    price.append(i.text)
price

In [184]:
#creating DataFrame for the scraped data
import pandas as pd
df=pd.DataFrame()
df['INDEX']=range(1,20)
df['PM Name']=Name[:19]
df['Born-Dead']=Born-Dead[:19]
df['Term of office']=Term_of_office[:19]
df['Remark']=Remark[:19]
df.set_index('INDEX',inplace=True)
df

NameError: name 'Born' is not defined

In [ ]:
//div[@class='table-box']/tbody/tr/td[2]

# Question 10

In [119]:
driver = webdriver.Chrome()

In [120]:
url = "https://www.motor1.com/"
driver.get(url)

In [121]:
driver.maximize_window()

In [122]:
search=driver.find_element(By.XPATH,"//input[@class='m1-search-panel-input m1-search-form-text']")

In [123]:
search.send_keys('50 most expensive cars')

In [124]:
btn=driver.find_element(By.XPATH,"//button[@class='m1-search-panel-button m1-search-form-button-animate icon-search-svg']")

In [125]:
btn.click()

In [126]:
img=driver.find_element(By.XPATH,"//picture[@class='lazyload']")

In [127]:
img.click()

In [137]:
car_name=driver.find_elements(By.XPATH,"//h3[@class='subheader']")
car=[]
for i in car_name[:50]:
    car.append(i.text)
car

['Aston Martin Valour',
 'McLaren Elva',
 'Czinger 21C',
 'Ferrari Monza',
 'Gordon Murray T.33',
 'Koenigsegg Gemera',
 'Zenvo TSR-S',
 'Hennessey Venom F5',
 'Bentley Bacalar',
 'Hispano Suiza Carmen Boulogne',
 'Bentley Mulliner Batur',
 'Deus Vayanne',
 'SSC Tuatara',
 'Lotus Evija',
 'Aston Martin Vulcan',
 'Delage D12',
 'Ferrari Daytona SP3',
 'McLaren Speedtail',
 'Rimac Nevera',
 'Pagani Utopia',
 'Pininfarina Battista',
 'Gordon Murray T.50',
 'Lamborghini Countach',
 'Mercedes-AMG Project One',
 'Zenvo Aurora',
 'Aston Martin Victor',
 'Hennessey Venom F5 Roadster',
 'Koenigsegg Jesko',
 'Aston Martin Valkyrie',
 'W Motors Lykan Hypersport',
 'McLaren Solus',
 'Lamborghini Sian',
 'Koenigsegg CC850',
 'Bugatti Chiron Super Sport 300+',
 'Lamborghini Veneno',
 'Bugatti Bolide',
 'Pininfarina B95 Speedster',
 'Bugatti Mistral',
 'Pagani Huayra Imola',
 'Bugatti Divo',
 'SP Automotive Chaos',
 'Pagani Codalunga',
 '777 Hypercar',
 'Mercedes-Maybach Exelero',
 'Bugatti Centodieci',
 'Bugatti Chiron Profilée',
 'Rolls-Royce Sweptail',
 'Bugatti La Voiture Noire',
 'Rolls-Royce Boat Tail*',
 'Rolls-Royce La Rose Noire Droptail']

In [140]:
car_price=driver.find_elements(By.XPATH,"//strong")
price=[]
for i in car_price[:50]:
    price.append(i.text)
price

['Price: $1.5 Million',
 'Price: $1.7 Million',
 'Price: $1.7 Million',
 'Price: $1.7 Million',
 'Price: $1.7 Million',
 'Price: $1.7 Million',
 'Price: $1.7 Million',
 'Price: $1.8 Million',
 'Price: $1.9 Million',
 'Price: $1.9 Million',
 'Price: $2.0 Million',
 'Price: $2.0 Million',
 'Price: $2.0 Million',
 'Price: $2.1 Million',
 'Price: $2.3 Million',
 'Price: $2.3 Million',
 'Price: $2.3 Million',
 'Price: $2.3 Million',
 'Price: $2.4 Million',
 'Price: $2.5 Million',
 'Price: $2.5 Million',
 'Price: $2.6 Million',
 'Price: $2.6 Million',
 'Price: $2.7 Million',
 'Price: $2.8 Million',
 'Price: $3.0 Million',
 '$3.0 Million',
 'Price: $3.0 Million',
 'Price: $3.2 Million',
 'Price: $3.4 Million',
 '$3.5 Million',
 'Price: $3.6 million',
 'Price: $3.7 Million',
 'Price: $3.9 Million',
 'Price: $4.5 Million',
 'Price: $4.7 Million',
 'Price: $4.8 Million',
 'Price: $5.0 Million',
 'Price: $5.4 Million',
 'Price: $5.8 Million',
 'Price: $6.4 Million',
 'Price: $7.4 Million',
 'Price: $7.5 Million',
 'Price: $8.0 Million',
 'Price: $9.0 Million',
 'Price: $10.8 Million',
 'Price: $12.8 Million',
 'Price: $13.4 Million',
 'Price: $28.0 Million (est.)',
 'Price: $30 Million (est.)']

In [143]:
#creating DataFrame for the scraped data
import pandas as pd
df=pd.DataFrame()
df['INDEX']=range(1,51)
df['Car Name']=car[:50]
df['Price']=price[:50]
df.set_index('INDEX',inplace=True)
df

                                 Car Name                        Price
INDEX
1                     Aston Martin Valour          Price: $1.5 Million
2                            McLaren Elva          Price: $1.7 Million
3                             Czinger 21C          Price: $1.7 Million
4                           Ferrari Monza          Price: $1.7 Million
5                      Gordon Murray T.33          Price: $1.7 Million
6                       Koenigsegg Gemera          Price: $1.7 Million
7                             Zenvo TSR-S          Price: $1.7 Million
8                      Hennessey Venom F5          Price: $1.8 Million
9                         Bentley Bacalar          Price: $1.9 Million
10          Hispano Suiza Carmen Boulogne          Price: $1.9 Million
11                 Bentley Mulliner Batur          Price: $2.0 Million
12                           Deus Vayanne          Price: $2.0 Million
13                            SSC Tuatara          Price: $2.0 Million
14                            Lotus Evija          Price: $2.1 Million
15                    Aston Martin Vulcan          Price: $2.3 Million
16                             Delage D12          Price: $2.3 Million
17                    Ferrari Daytona SP3          Price: $2.3 Million
18                      McLaren Speedtail          Price: $2.3 Million
19                           Rimac Nevera          Price: $2.4 Million
20                          Pagani Utopia          Price: $2.5 Million
21                   Pininfarina Battista          Price: $2.5 Million
22                     Gordon Murray T.50          Price: $2.6 Million
23                   Lamborghini Countach          Price: $2.6 Million
24               Mercedes-AMG Project One          Price: $2.7 Million
25                           Zenvo Aurora          Price: $2.8 Million
26                    Aston Martin Victor          Price: $3.0 Million
27            Hennessey Venom F5 Roadster                 $3.0 Million
28                       Koenigsegg Jesko          Price: $3.0 Million
29                  Aston Martin Valkyrie          Price: $3.2 Million
30              W Motors Lykan Hypersport          Price: $3.4 Million
31                          McLaren Solus                 $3.5 Million
32                       Lamborghini Sian          Price: $3.6 million
33                       Koenigsegg CC850          Price: $3.7 Million
34        Bugatti Chiron Super Sport 300+          Price: $3.9 Million
35                     Lamborghini Veneno          Price: $4.5 Million
36                         Bugatti Bolide          Price: $4.7 Million
37              Pininfarina B95 Speedster          Price: $4.8 Million
38                        Bugatti Mistral          Price: $5.0 Million
39                    Pagani Huayra Imola          Price: $5.4 Million
40                           Bugatti Divo          Price: $5.8 Million
41                    SP Automotive Chaos          Price: $6.4 Million
42                       Pagani Codalunga          Price: $7.4 Million
43                           777 Hypercar          Price: $7.5 Million
44               Mercedes-Maybach Exelero          Price: $8.0 Million
45                     Bugatti Centodieci          Price: $9.0 Million
46                Bugatti Chiron Profilée         Price: $10.8 Million
47                   Rolls-Royce Sweptail         Price: $12.8 Million
48               Bugatti La Voiture Noire         Price: $13.4 Million
49                 Rolls-Royce Boat Tail*  Price: $28.0 Million (est.)
50     Rolls-Royce La Rose Noire Droptail    Price: $30 Million (est.)